name: CD

on:
  push:
    tags:
      - v*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Bootstrap
      run: make bootstrap
    - name: Build
      run: make NEW_VERSION=${{ GITHUB_REF_NAME }} package
    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: slack
        path: .target/linux_amd64/slack

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      build
    steps:
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ GITHUB_REF_NAME }}
        release_name: ${{ GITHUB_REF_NAME }}
        draft: false
        prerelease: false
    outputs:
      uploadURL: ${{ steps.create-release.outputs.upload_url }}

  artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    needs:
      release
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: slack
    - name: Make Artifact Executable # See https://github.com/actions/upload-artifact/issues/38
      run: chmod +x .target/linux_amd64/slack
    - name: Upload Asset
      id: upload-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.uploadURL }}
        asset_path: .target/linux_amd64/slack
        asset_name: slack-linux-amd64
        asset_content_type: "application"
